### ISSUE TITLE
Use AI to write Csound instruments!

### ISSUE THREAD

**Issue by gogins** [gogins/michael.gogins.studio#77]
I just used ChatGPT freebie to do this. Here's my prompt:

> Can you write me a Csound instrument definition that uses one FM oscillator modifying another FM oscillator, with stereo output to a reverb unit.

The first response was a plain old one stage FM instrument of mediocre quality but it worked right out of the box. I clarified the cascading business and got the attached file. Still mediocre, but it's amazing that it works and it is truly fast.

[chatgpt_fm.txt](https://github.com/user-attachments/files/15929382/chatgpt_fm.txt)

**Comment by csounder** [comment]
Yes, this is pretty exciting.  I think we need to better train ChatGPT about Csound, but it already seems to know quite a bit.
- it is fun to interact with it.  I have done a bit and spent some fun days and nights challanging, teaching, correcting.  Not sure it helps any, but maybe.  
-
